<?php namespace ProcessWire;


class InlineCompleteTinyMCEAction extends WireData implements Module {

	public static function getModuleInfo() {
		
		return array(
			"title"		=>	"Autocomplete Action Base Class",
			"summary"	=>	"Base class for actions for ProcessInlineCompleteTinyMCE",
			"version"	=>	"0.0.5",
			"autoload"	=>	function() {
				$p = wire('page');
				if($p->template != "admin") return false;
				if($p->process === "ProcessPageEdit" || $p->process === "ProcessField"|| $p->process === "ProcessInlineCompleteTinyMCE") {
					return true;
				}
				return false;
			},
		);
	}
	
	/**
	 * Set the name of the action to the lowercased part of the module name following "InlineCompleteAction".
	 * The name for all action modules needs to start with "InlineCompleteAction".
	 */
	public function init() {
		if($this->className != "InlineCompleteTinyMCEAction") {
			$name = strtolower(str_replace("InlineCompleteTinyMCEAction", "", $this->className));
			$this->set("name", $name);
		}
		if(strpos($this->className, "InlineCompleteTinyMCEAction") === 0)
			$this->addHookAfter("ProcessInlineCompleteTinyMCE::registerActions", $this, "registerAction");
		
		$this->set('limit', 30);
		$this->set('dropdownWidth', 200);
		$this->set('dropdownHeight', 400);
		$this->set('resultTpl', '<li>{name}</li>');
		$this->set('insertTpl', '{value}');
	}
	
	/**
	 * Get the trigger character.
	 *
	 * You can override this method in action implementations if the action
	 * doesn't have a configurable trigger like the HannaCode action does,
	 * where the trigger character is the same as the open tag configured
	 * in Hanna Code settings.
	 *
	 * If your implementation supports multiple triggers, you can return
	 * an array here. Your module needs to evaluate the post parameter
	 * "trigger" in that case to determine which trigger routine it should
	 * execute.
	 *
	 */
	public function getTrigger() {
		
		return $this->trigger;
		
	}
	
	/**
	 *
	 * Simply add this instance to the return of ProcessInlineCompleteTinyMCE
	 *
	 */
	public function registerAction(HookEvent $event) {
		if($this->className != "InlineCompleteTinyMCEAction") {
			$actions = $event->return;
			$actions[] = $this;
			$event->return = $actions;
		}
	}

	/**
	 *
	 * Retrieve the CSS stylesheet. Looks first in the site/templates/styles, then in
	 * the module's directory for a file matching CLASSNAME.css and, if found, adds
	 * it to the styles.
	 *
	 */
	public function getCss() {
		$cssPath = $this->config->paths->templates . "styles" . \DIRECTORY_SEPARATOR . $this->className . ".css";
		if(file_exists($cssPath)) {
			return $this->config->urls->{$this->className} . "styles/" . $this->className . ".css";
		}

		$cssPath = $this->config->paths->{$this->className} . $this->className . ".css";
		if(file_exists($cssPath)) {
			return $this->config->urls->{$this->className} . $this->className . ".css";
		}
		
		return "";
	}
	
	/**
	 *
	 * Override this in your action implementation to return module-specific
	 * settings for the TinyMCE plugin, like the character that invokes the
	 * autocomplete or the dropdown label. Note that you don't have to add
	 * settings here that should be configurable by the user. Set those in
	 * init() and add a configuration field in ___getSettingsFields.
	 *
	 * See the README for ProcessInlineCompleteTinyMCE for a list of
	 * applicable settings. Simply return an associative array
	 * with these settings in your action class.
	 *
	 */
	public function ___getActionSettings() {
		return array(
			// The string after which the search pattern starts, will be the
			// same as typeAheadChar the most time, but it may differ for
			// multi-letter starting strings like with Hanna Codes ("[[")
			//"typeAheadAfter"	=>	"~~",
		);
	}
	
	/**
	 * Fill the placeholders in the template string with properties from
	 * the supplied data object.
	 *
	 * Example: replaces {name} with $data->name.
	 */
	protected function fillTpl($tpl, $data) {
		return preg_replace_callback('/\\{([^}]+)\\}/', function($match) use($data) {
			$fld = $match[1];
			if(count($match) && isset($data->$fld)) {
				return $data->$fld;
			}
			return "";
		}, $tpl);
	}
	
	/**
	 * Configurable settings. These inputfields will be added to each
	 * TinyMCE field's input settings.
	 */
	public function ___getSettingsFields($field, $prefix) {
		$wrap = new InputfieldWrapper();
		
		$f = $this->modules->get("InputfieldText");
		$f->attr('name', 'limit');
		$f->attr('value', $this->limit);
		$f->attr('size', 5);
		$f->label = $this->_("Result limit");
		$f->description = $this->_("Return at most this many results at once. Default is 30.");
		$wrap->add($f);
		
		$f = $this->modules->get("InputfieldText");
		$f->label = $this->_("Result Template");
		$f->attr('name', 'resultTpl');
		$f->attr('value', $this->resultTpl);
		$f->description = $this->_("Template for the dropdown list label");
		$wrap->add($f);
		
		$f = $this->modules->get("InputfieldText");
		$f->label = $this->_("Insert Template");
		$f->attr('name', 'insertTpl');
		$f->attr('value', $this->insertTpl);
		$f->description = $this->_("Template for inserting the result into CKEditor, uses placeholders in curly braces, e.g. {value}");
		$wrap->add($f);

		return $wrap;
	}

}
